### ISSUE TITLE
End Call Error

### ISSUE THREAD

**Issue by Sodabeh-Taherpanah** [NikValdez/VideoChatTut#7]
I take this error  after clicking on " End Call" button.  Do anybody have a solution?
process is not defined
ReferenceError: process is not defined
    at emitReadable (http://localhost:3000/static/js/bundle.js:56893:5)
    at onEofChunk (http://localhost:3000/static/js/bundle.js:56873:5)
    at readableAddChunk (http://localhost:3000/static/js/bundle.js:56657:5)
    at Readable.push (http://localhost:3000/static/js/bundle.js:56646:10)
    at http://localhost:3000/static/js/bundle.js:60563:44

**Comment by Sodabeh-Taherpanah** [comment]
Actually, I solve it. this happened because simple-peer did not have finished and you tried to destroy the socket's connection. 
please add those lines to the index. js, at the very first line if you are using react. Be sure that you installed "process" before.

import * as process from "process";

window.global = window;
window.process = process;
window.Buffer = [];
